name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install Package
  # You may pin to the exact commit or the version.
  # uses: ConorMacBride/install-package@3e7ad059e07782ee54fa35f827df52aae0626f30
      uses: ConorMacBride/install-package@v1.1.0
      with:
       apt: build-essential bison flex m4 texinfo libgmp-dev libmpc-dev libmpfr-dev ppl-dev libppl-dev cloog-ppl libcloog-ppl-dev
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
